### PR TITLE
use list length for range function

### PR DESCRIPTION
**Pull request by cupOJoseph**

### CODE REVIEW

**Comment by cupOJoseph** [comment]
fixes #24, although there are other syntax issues.

**Comment by sweetmantech** [comment]
I'm excited to see this implemented!

Do we know why it is taking IBM team so long to review?

Nearly 2 months without merging.

Maybe we need to assign merger? 

image

**Comment by sweetmantech** [comment]
`Assign Pull Requests to: amchaney`

**Comment by cupOJoseph** [comment]
I think there are some other issues too. I solved that one thing but had other bugs, never actually got it running... wish it worked

**Comment by sweetmantech** [comment]
:( does IBM still support this? @amchaney ?

**Comment by amchaney** [comment]
Hey, IBM has never supported this.  I did this in my free time, and testing a one line range check change hasn't been on the top of my personal time recently.  If you tried it @SweetmanTech and it didn't break your build, I'd merge it, but @jschiarizzi also said he never got it running completely, so really I'd prefer to wait on a full fix before I review a PR.

**Comment by amchaney** [comment]
FYI, this was never supported under Windows, so if you want feel free to manage your own branch that's why it is open sourced :-)

**Comment by cupOJoseph** [comment]
Probably a good idea since I never got it running properly. :)

Maybe it will help someone getting it running elsewhere though, as a reference.

**Pull request closed without merging**
