### PR TITLE
Typo on string #15

### PR DESCRIPTION
**Pull request by kant**

### CODE REVIEW

**Review by amchaney — APPROVED** [review]
one spelling error, and a punctuation mark change

**Comment by bclark288** [comment]
I'm a little new to GitHub.  I notice there are two of you active and I'd like to join the conversation. I have used watson beats on about 30 songs so far and I have made a couple changes to make my work easier.  The biggest change was to create only one midi file for each layer instead of having a midi file for each layer and section.  Is that something others would be interested in?  Also, I'm now looking at how chord progressions and melodies are created and it would be great to have someone who can help me understand the code.

**Comment by amchaney** [comment]
Hi @bclark288  ... I do think making one midi per instrument would be a good _option_ for people running the watson beat code.  I don't want to use it that way, since it makes it harder for me to edit the tracks after processing, but it would make it easier to get started.  If you want to contribute, the way forward would be adding a command line option to request that there is one instrument per track, then switching on that option while writing the midi files.  You would create a pull request containing _just_ these changes, then someone (most likely me) would evaluate the changes to make sure they worked and, if they did, they would be merged into the master branch.

**Comment by bclark288** [comment]
Hi,

I have made the changes to make one midi per layer a command line option.  As I mentioned, I’m a little new to GitHub.  I did some reading about pull requests, but I noticed there aren’t any branches other than the master.  I don’t want to step on anyone’s code, so I’m a little unsure what to do next.

**Comment by amchaney** [comment]
@bclark288 ... this is a good article to read on how you should create a Pull Request (PR)
https://akrabat.com/the-beginners-guide-to-contributing-to-a-github-project/

**Comment by bclark288** [comment]
Hi,

Thanks for the article.  It was very helpful.  I’m ready to create the pull request now.  It’s been a few weeks (I was traveling), so I thought I would give you a heads-up.  Let me know if it’s ok to go ahead and create the PR.

**Comment by amchaney** [comment]
sure, create a PR! I might not review it right away (I'm 3 PRs behind on my day job right now) but I promise I will get to it eventually :-)

**Comment by bclark288** [comment]
I have created the PR.  No big hurry on getting it done.  I am curious about what is happening with the project.  Are you with IBM?  I’m a music technology student at Ga. Tech.  This software seems to be a very good fit with the research I want to do over the next couple of years.  It would be nice to know what’s in store for this project.

**Pull request merged**
